[package]
name = "swiftness-solana"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
solana-program = { git = "https://github.com/Okm165/solana.git", branch = "fix/deps" }
swiftness_air = { git = "https://github.com/iosis-tech/swiftness.git", rev = "29c780d4", default-features = false, features = [
    "recursive",
    "keccak_160_lsb",
    "stone6",
] }
swiftness_stark = { git = "https://github.com/iosis-tech/swiftness.git", rev = "29c780d4", default-features = false, features = [
    "recursive",
    "keccak_160_lsb",
    "stone6",
] }

[dev-dependencies]
swiftness = { git = "https://github.com/iosis-tech/swiftness.git", rev = "29c780d4", default-features = false, features = [
    "recursive",
    "keccak_160_lsb",
    "stone6",
] }
swiftness_proof_parser = { git = "https://github.com/iosis-tech/swiftness.git", rev = "29c780d4" }

[lib]
name = "swiftness"
crate-type = ["cdylib", "lib"]
